// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-B53QVeUtnqnzLgx6trDlJ6ZaFCwjtyY',
    appId: '1:72310219395:web:ccce1edf032bdc5ca731b6',
    messagingSenderId: '72310219395',
    projectId: 'fan-page-ed9b6',
    authDomain: 'fan-page-ed9b6.firebaseapp.com',
    storageBucket: 'fan-page-ed9b6.appspot.com',
    measurementId: 'G-M7DYFDPBY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdhJw3RSPnrQYfMhIzOO8IgUlUtWlPlF8',
    appId: '1:72310219395:android:f91c4025ce1e90a1a731b6',
    messagingSenderId: '72310219395',
    projectId: 'fan-page-ed9b6',
    storageBucket: 'fan-page-ed9b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByKE7tCEP8ZPYlQT4dB258TEazVRTKHIc',
    appId: '1:72310219395:ios:6e48b7c84b891c9aa731b6',
    messagingSenderId: '72310219395',
    projectId: 'fan-page-ed9b6',
    storageBucket: 'fan-page-ed9b6.appspot.com',
    iosClientId: '72310219395-s94kticoi471fs8dkr2vdrtps9irsk0l.apps.googleusercontent.com',
    iosBundleId: 'com.ex',
  );
}
